# Generated by Django 2.2.2 on 2019-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_title', models.CharField(max_length=255)),
                ('j_desc', models.TextField()),
                ('j_sal', models.IntegerField()),
                ('j_location', models.CharField(max_length=255)),
            ],
        ),
    ]
