# Generated by Django 2.2.2 on 2019-07-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Product',
        ),
    ]
